name: my_music_player
description: "MY Music Player - 本地音乐播放与管理软件"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  # UI 图标
  cupertino_icons: ^1.0.8
  
  # 状态管理
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  
  # 本地数据库
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  
  # 音频元数据读写
  audiotags: ^1.4.1
  
  # 桌面端集成
  window_manager: ^0.4.3
  file_picker: ^8.0.3
  
  # 工具库
  path: ^1.9.0
  path_provider: ^2.1.3
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  
  # 代码生成
  build_runner: ^2.4.8
  isar_generator: ^3.1.0+1
  riverpod_generator: ^2.4.0

flutter:
  uses-material-design: true
